<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.CN.NET.Sdk/13.1.0">
    <PropertyGroup>
        <Version>1.0.0.0</Version>
        <Description>woc！触发组！</Description>
        <PackageProjectUrl>https://github.com/NiGuangOwO/LuckyStar</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <Authors>NiGuangOwO</Authors>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ecommons\ECommons\ECommons.csproj" />
    </ItemGroup>
</Project>